### ISSUE TITLE
Add the Jazzband contributing guideline

### ISSUE THREAD

**Issue by jezdez** [jazzband/django-discover-jenkins#23]
Please add a `CONTRIBUTING.md` file to the repo that contains the snippet listed on https://jazzband.co/docs/guidelines#contributions to show to users opening issues or PRs what the contributing guidelines are.

**Comment by camilonova** [comment]
@jezdez Done.

**Comment by jezdez** [comment]
@camilonova \o/

**Comment by camilonova** [comment]
:)
